language: python

python:
    - "2.6"
    - "2.7"
    - "3.4"

env:
  - TOX_ENV=py26-django16
  - TOX_ENV=py27-django16
  - TOX_ENV=py34-django16
  - TOX_ENV=coverage

install:
  - pip install tox 

script:
  - tox -e $TOX_ENV

